/**
 * Bundles the ARCH §5 offline insurance: turns a batch produced by a real run
 * into media *files* in the app, because fal and ElevenLabs URLs expire and a
 * link that 403s at the demo is worth nothing.
 *
 *   npm run dev                                     # in one terminal
 *   npm run smoke -- ./worksheet.jpg on-level       # in another
 *   npm run bundle:fallbacks -- ./batch-on-level.json
 *   npm run bundle:fallbacks -- ./batch-challenge.json challenge-batch
 *
 * Automates all four manual steps in `mobile/src/assets/fallback/README.md`:
 *   1. validate the source batch against the real `BatchSpec`;
 *   2. download every `imageUrl`/`audioUrl` into the fallback asset folder as
 *      `g<group>-s<slide>.<ext>` — http(s) URLs are fetched, `data:` URIs are
 *      decoded inline, so it works whichever way `/api/assets` hosts audio;
 *   3. write the fresh spec back with those now-dead URLs removed (the runtime
 *      re-attaches media by key, not by URL);
 *   4. regenerate the `bundledMedia` map in `mobile/src/lib/fallback.ts`, which
 *      needs a literal `require()` per asset because Metro resolves paths at
 *      build time.
 *
 * Keys are `<variant>-g<groupIndex>-s<slideIndex>` — `b` for the on-level batch,
 * `c` for the Challenge one — with `slideIndex` restarting at 0 in each group
 * and running across that group's lessons, exactly what `attachBundledMedia`
 * looks up. The variant keeps the two batches in separate key spaces; sharing
 * one would make the Challenge batch play the on-level batch's media on the
 * Make-it-harder beat. Step 4 still regenerates from the folder rather than
 * from this run alone, so bundling one batch never deregisters the other.
 */
import { readdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { extname, resolve } from 'node:path';
import { BatchSpec } from '../lib/schema';

/** All relative to `api/`, which is where the npm script runs. */
const ASSET_DIR = '../mobile/src/assets/fallback';
const FALLBACK_TS = '../mobile/src/lib/fallback.ts';
/** The `require()` prefix as written from inside `mobile/src/lib/`. */
const REQUIRE_PREFIX = '../assets/fallback';

/** Polite to fal's CDN and still fast for the dozen files a batch produces. */
const CONCURRENCY = 4;
const TIMEOUT_MS = 30_000;

const BEGIN_MARK = '--- generated by scripts/bundle-fallbacks.ts ---';
const END_MARK = '--- end generated ---';

const TARGETS: Record<string, string> = {
  batch: 'batch',
  'challenge-batch': 'challenge-batch',
  challenge: 'challenge-batch',
  'on-level': 'batch',
  easy: 'batch',
};

/** Key-space prefix per target — see the header note on why these are separate. */
const VARIANTS: Record<string, string> = {
  batch: 'b',
  'challenge-batch': 'c',
};

type Kind = 'image' | 'audio';

/** Content types the two providers actually return, mapped to a file suffix. */
const EXTENSIONS: Record<Kind, Record<string, string>> = {
  image: {
    'image/jpeg': 'jpg',
    'image/jpg': 'jpg',
    'image/pjpeg': 'jpg',
    'image/png': 'png',
    'image/webp': 'webp',
  },
  audio: {
    'audio/mpeg': 'mp3',
    'audio/mpeg3': 'mp3',
    'audio/mp3': 'mp3',
    'audio/x-mpeg-3': 'mp3',
  },
};

const KNOWN_EXTENSIONS: Record<Kind, string[]> = {
  image: ['jpg', 'png', 'webp'],
  audio: ['mp3'],
};

interface Job {
  key: string;
  kind: Kind;
  source: string;
}

interface Downloaded extends Job {
  file: string;
  bytes: number;
}

/* ------------------------------------------------------------------ *
 * Fetch / decode
 * ------------------------------------------------------------------ */

const DATA_URI = /^data:([^,;]*)((?:;[^,]*)*),(.*)$/s;

/** Both shapes S4 can hand back: a hosted URL, or an inline base64 payload. */
async function loadBytes(source: string): Promise<{ bytes: Buffer; mime: string }> {
  if (source.startsWith('data:')) {
    const match = DATA_URI.exec(source);
    if (!match) throw new Error('malformed data: URI');
    const [, mime, parameters, payload] = match;
    const bytes = parameters.includes(';base64')
      ? Buffer.from(payload, 'base64')
      : Buffer.from(decodeURIComponent(payload), 'latin1');
    if (bytes.length === 0) throw new Error('data: URI decoded to zero bytes');
    return { bytes, mime: mime.toLowerCase() };
  }

  if (!/^https?:\/\//i.test(source)) {
    throw new Error(`unsupported URL scheme (${source.slice(0, 24)}…)`);
  }

  const response = await fetch(source, { signal: AbortSignal.timeout(TIMEOUT_MS) });
  if (!response.ok) throw new Error(`HTTP ${response.status} ${response.statusText}`);

  const bytes = Buffer.from(await response.arrayBuffer());
  if (bytes.length === 0) throw new Error('server returned zero bytes');
  const mime = (response.headers.get('content-type') ?? '').split(';')[0].trim().toLowerCase();
  return { bytes, mime };
}

/** Magic numbers, for when a host sends `application/octet-stream` or nothing. */
function sniff(bytes: Buffer): string | undefined {
  if (bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return 'png';
  if (bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return 'jpg';
  if (bytes.subarray(0, 4).toString('ascii') === 'RIFF' && bytes.subarray(8, 12).toString('ascii') === 'WEBP') {
    return 'webp';
  }
  if (bytes.subarray(0, 3).toString('ascii') === 'ID3') return 'mp3';
  // MPEG audio frame sync: 11 set bits.
  if (bytes[0] === 0xff && (bytes[1] & 0xe0) === 0xe0) return 'mp3';
  return undefined;
}

function extensionFor(kind: Kind, mime: string, bytes: Buffer, source: string): string {
  const byMime = EXTENSIONS[kind][mime];
  if (byMime) return byMime;

  const sniffed = sniff(bytes);
  if (sniffed && KNOWN_EXTENSIONS[kind].includes(sniffed)) return sniffed;

  // Last resort: fal signs URLs but keeps the extension on the path.
  const fromPath = extname(safePathname(source)).replace('.', '').toLowerCase();
  const normalised = fromPath === 'jpeg' ? 'jpg' : fromPath;
  if (KNOWN_EXTENSIONS[kind].includes(normalised)) return normalised;

  throw new Error(`cannot tell what kind of ${kind} this is (content-type "${mime || 'none'}")`);
}

function safePathname(source: string): string {
  try {
    return new URL(source).pathname;
  } catch {
    return '';
  }
}

/* ------------------------------------------------------------------ *
 * Download
 * ------------------------------------------------------------------ */

/**
 * Writes through a temp file and renames, so a timeout half way through a
 * 300KB mp3 cannot leave a truncated asset that only fails on stage.
 */
async function download(job: Job, directory: string): Promise<Downloaded> {
  const { bytes, mime } = await loadBytes(job.source);
  const extension = extensionFor(job.kind, mime, bytes, job.source);
  const file = `${job.key}.${extension}`;
  const target = resolve(directory, file);
  const temporary = `${target}.partial`;

  try {
    await writeFile(temporary, bytes);
    await rename(temporary, target);
  } catch (error) {
    await rm(temporary, { force: true });
    throw error;
  }

  // A rerun that lands on a different extension must not leave the old one
  // behind, or step 4 would register both.
  for (const stale of KNOWN_EXTENSIONS[job.kind]) {
    if (stale !== extension) await rm(resolve(directory, `${job.key}.${stale}`), { force: true });
  }

  return { ...job, file, bytes: bytes.length };
}

/** Bounded worker pool — enough parallelism to be quick, not enough to be rude. */
async function runPool<T, R>(items: T[], limit: number, work: (item: T) => Promise<R>): Promise<R[]> {
  const results = new Array<R>(items.length);
  let next = 0;

  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (let i = next++; i < items.length; i = next++) {
      results[i] = await work(items[i]);
    }
  });

  await Promise.all(workers);
  return results;
}

/* ------------------------------------------------------------------ *
 * Spec rewriting
 * ------------------------------------------------------------------ */

function collectJobs(batch: BatchSpec, variant: string): { jobs: Job[]; skipped: string[] } {
  const jobs: Job[] = [];
  const skipped: string[] = [];

  batch.groups.forEach((group, groupIndex) => {
    let slideIndex = 0;
    for (const lesson of group.lessons) {
      for (const slide of lesson.slides) {
        const key = `${variant}-g${groupIndex}-s${slideIndex++}`;
        if (slide.imageUrl) jobs.push({ key, kind: 'image', source: slide.imageUrl });
        if (slide.audioUrl) jobs.push({ key, kind: 'audio', source: slide.audioUrl });
        if (!slide.imageUrl && !slide.audioUrl) skipped.push(key);
      }
    }
  });

  return { jobs, skipped };
}

/** The bundled spec ships without URLs: the app re-attaches media by key. */
function stripUrls(batch: BatchSpec): BatchSpec {
  return {
    ...batch,
    groups: batch.groups.map((group) => ({
      ...group,
      lessons: group.lessons.map((lesson) => ({
        slides: lesson.slides.map((slide) => {
          const { imageUrl: _image, audioUrl: _audio, ...rest } = slide;
          return rest;
        }),
      })),
    })),
  };
}

/* ------------------------------------------------------------------ *
 * bundledMedia regeneration
 * ------------------------------------------------------------------ */

const ASSET_FILE = /^(b|c)-g(\d+)-s(\d+)\.(jpg|png|webp|mp3)$/;

/**
 * Reads the folder rather than this run's manifest, so bundling the challenge
 * batch after the on-level one does not deregister what is still on disk.
 */
async function scanAssets(directory: string): Promise<Map<string, { image?: string; audio?: string }>> {
  const entries = (await readdir(directory)).filter((name) => ASSET_FILE.test(name)).sort();
  const byKey = new Map<
    string,
    { image?: string; audio?: string; variant: string; group: number; slide: number }
  >();

  for (const name of entries) {
    const [, variant, group, slide, extension] = ASSET_FILE.exec(name)!;
    const key = `${variant}-g${Number(group)}-s${Number(slide)}`;
    const entry = byKey.get(key) ?? { variant, group: Number(group), slide: Number(slide) };
    if (extension === 'mp3') entry.audio = name;
    else entry.image = name;
    byKey.set(key, entry);
  }

  const ordered = [...byKey.entries()].sort(
    ([, a], [, b]) => a.variant.localeCompare(b.variant) || a.group - b.group || a.slide - b.slide,
  );
  return new Map(ordered.map(([key, entry]) => [key, { image: entry.image, audio: entry.audio }]));
}

function renderRegion(assets: Map<string, { image?: string; audio?: string }>, indent: string): string[] {
  const lines = [`${indent}// ${BEGIN_MARK}`];

  if (assets.size === 0) {
    lines.push(`${indent}// (nothing bundled yet — run \`npm run bundle:fallbacks\` in api/)`);
  }

  for (const [key, { image, audio }] of assets) {
    const parts: string[] = [];
    if (image) parts.push(`image: require('${REQUIRE_PREFIX}/${image}')`);
    if (audio) parts.push(`audio: require('${REQUIRE_PREFIX}/${audio}')`);
    lines.push(`${indent}'${key}': { ${parts.join(', ')} },`);
  }

  lines.push(`${indent}// ${END_MARK}`);
  return lines;
}

/**
 * Rewrites only the delimited region, adding the delimiters on first run.
 * Anything hand-written elsewhere in the map — or in the file — survives.
 */
function rewriteBundledMedia(source: string, assets: Map<string, { image?: string; audio?: string }>): string {
  const eol = source.includes('\r\n') ? '\r\n' : '\n';
  const lines = source.split(eol);

  const begin = lines.findIndex((line) => line.includes(BEGIN_MARK));
  const end = lines.findIndex((line) => line.includes(END_MARK));

  if (begin !== -1 && end > begin) {
    const indent = lines[begin].slice(0, lines[begin].indexOf('//'));
    lines.splice(begin, end - begin + 1, ...renderRegion(assets, indent));
    return lines.join(eol);
  }

  const declaration = lines.findIndex((line) => /const bundledMedia\b/.test(line));
  if (declaration === -1) throw new Error(`no \`const bundledMedia\` declaration in ${FALLBACK_TS}`);

  const close = lines.findIndex((line, i) => i > declaration && /^\s*};\s*$/.test(line));
  if (close === -1) throw new Error(`could not find the end of \`bundledMedia\` in ${FALLBACK_TS}`);

  lines.splice(close, 0, ...renderRegion(assets, '  '));
  return lines.join(eol);
}

/* ------------------------------------------------------------------ *
 * Main
 * ------------------------------------------------------------------ */

/**
 * Bails with a non-zero exit *without* `process.exit()`: undici holds its
 * sockets open for a beat after a download, and tearing the process down under
 * them trips a libuv assertion on Windows and reports 127 instead of 1.
 */
class Bail extends Error {}

async function main() {
  const [sourcePath, targetArg] = process.argv.slice(2);
  if (!sourcePath) {
    throw new Bail('usage: npm run bundle:fallbacks -- <batch-*.json> [batch|challenge-batch]');
  }

  const raw = await readFile(resolve(process.cwd(), sourcePath), 'utf8');
  const parsed = BatchSpec.safeParse(JSON.parse(raw));
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `    ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');
    throw new Bail(`✗ ${sourcePath} is not a valid Batch Spec:\n\n${issues}`);
  }

  const batch = parsed.data;
  const target = TARGETS[targetArg ?? batch.difficulty];
  if (!target) {
    throw new Bail(`unknown target "${targetArg}" — expected "batch" or "challenge-batch"`);
  }

  const directory = resolve(process.cwd(), ASSET_DIR);
  const { jobs, skipped } = collectJobs(batch, VARIANTS[target]);

  console.log(`\nbundling ${sourcePath} → ${ASSET_DIR}/${target}.json`);
  console.log(`  ${batch.groups.length} groups, ${jobs.length} assets, ${CONCURRENCY} at a time\n`);

  const settled = await runPool(jobs, CONCURRENCY, async (job) => {
    try {
      const done = await download(job, directory);
      console.log(
        `  ✓ ${done.file.padEnd(14)} ${String(done.bytes).padStart(9)} bytes  ` +
          `${job.source.startsWith('data:') ? 'data: URI' : 'downloaded'}`,
      );
      return { job, done };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`  ✗ ${`${job.key} ${job.kind}`.padEnd(14)} ${message}`);
      return { job, error: message };
    }
  });

  const failures = settled.filter((result) => 'error' in result);
  if (failures.length > 0) {
    throw new Bail(
      `${failures.length}/${jobs.length} asset(s) failed — nothing rewritten. ` +
        `Re-run once the source URLs are reachable (fal links expire).`,
    );
  }

  if (skipped.length > 0) {
    console.log(`\n  no media on ${skipped.length} slide(s): ${skipped.join(', ')}`);
  }

  const specPath = resolve(directory, `${target}.json`);
  await writeFile(specPath, `${JSON.stringify(stripUrls(batch), null, 2)}\n`);
  console.log(`\n  wrote ${ASSET_DIR}/${target}.json (imageUrl/audioUrl stripped)`);

  const fallbackPath = resolve(process.cwd(), FALLBACK_TS);
  const assets = await scanAssets(directory);
  const rewritten = rewriteBundledMedia(await readFile(fallbackPath, 'utf8'), assets);
  await writeFile(fallbackPath, rewritten);
  console.log(`  wrote ${FALLBACK_TS} — ${assets.size} key(s) in bundledMedia`);
  console.log(`\n  next: npm run validate:fallbacks\n`);
}

main().catch((error) => {
  console.error(`\n${error instanceof Bail || error instanceof Error ? error.message : error}\n`);
  process.exitCode = 1;
});
